name: Build and test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
    - name: ZIP built application     
      run: |
        cd ./publish
        zip -r ${{ env.ZIP_FILE }} .
        mv ./${{ env.ZIP_FILE }} ../
        cd ../          
      env:  
               ZIP_FILE: "versity"
